### ISSUE TITLE
Install dependency warnings.

### ISSUE THREAD

**Issue by ForestMist** [ForestMist/feri#19]
# Some dependency warnings are visible when installing Feri.

As of February 29, 2016 they are:
- ~~Less 2.6.0~~
  - ~~Depends on deprecated graceful-fs 3.0.8.~~
  - ~~Will be resolved when Less 2.6.1 is released.~~
- Mocha 2.4.5
  - Depends on glob 3.2.3 which depends on deprecated graceful-fs 2.0.3.
  - Mocha contributors are aware of the issue.
- Node-Sass 3.4.2
  - ~~Depends on gaze 0.5.2 which depends on globule 0.1.0 which depends on glob 3.1.21 which depends on deprecated graceful-fs 1.2.3 and deprecated lodash 1.0.2.~~
  - Depends on deprecated npmconf 2.1.2.
  - Node-Sass contributors are aware of both issues although in the case of npmconf, it sounds like it may not be fixed anytime soon.

Will check on warnings again when updating Feri dependencies to the latest versions.

**Comment by ForestMist** [comment]
Less 2.6.1 resolved its dependency warning and is included in Feri 0.3.0.

**Comment by ForestMist** [comment]
Node-Sass 3.6.0 resolved one of the dependency warnings and is included in Feri 0.3.4.

**Comment by gld1982ltd** [comment]
```sh
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
```

**Comment by ForestMist** [comment]
Thanks for the latest ones.

Since Feri uses a lot of other modules, and since open source is constantly changing, there are new warnings cropping up all the time. At least, it seems that way lately. Hehe.

**Comment by gld1982ltd** [comment]
Ever since node.js v5 came out....

**Comment by ForestMist** [comment]
The current warnings are...

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

The warnings Jade and Transformers both come from Jade. Pug, the replacement for jade is still in beta so I see no reason to remove Jade from Feri yet. These warnings are a non-issue as far as I am concerned.

The warning for Node-Gyp comes from SASS and while slightly annoying to see, it is also a non issue.

Marking issue as closed.
