### ISSUE TITLE
Add a quick start guide or tutorial

### ISSUE THREAD

**Issue by fernandocanizo** [ForestMist/feri#30]
Hello Daniel, before considering doing video tutorials, please take some time to add a quick-start guide on the `README` or maybe a tutorial. I got interested in your task runner and came to give it a try but I only get errors on the console. Surely I'm doing something wrong, but you'll get far more people giving a try if you manage to put up a quick an easy list of steps to get `feri` up and running.

**Comment by ForestMist** [comment]
I'm thinking the magical --init command is what is missing from the initial readme. A quick start guide sounds like a good idea. Thanks for adding this issue.

**Comment by ForestMist** [comment]
The `--init` command is now documented in a new Quickstart section. More info at https://github.com/ForestMist/feri#quickstart
